/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;

import Services.KhachHangServices;
import Services.KhachHangServicesImpl;
import ViewModels.HoaDonKhachHangView;
import ViewModels.QLKhachHang;

import java.util.ArrayList;

import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class KhachHangJPanel extends javax.swing.JPanel {

    KhachHangServices khachHangServices = new KhachHangServicesImpl();
    DefaultTableModel model;
    DefaultTableModel model2;
    ArrayList<QLKhachHang> listQLKH;
    ArrayList<HoaDonKhachHangView> listHDKH;
    int index;
    String _idKhachHang = "";
    String name = "";
    int _soTrangKH = 1;
    int _soTrangHD = 1;

    public KhachHangJPanel() {
        initComponents();
        name = txtTimKiem.getText();
        listQLKH = khachHangServices.search(name, getStartKH(_soTrangKH), getEndKH(_soTrangKH));
        loadData(listQLKH);
        lblSoTrangHD.setText(_soTrangHD + "");
        lblSoTrangKH.setText(_soTrangKH + "");
    }

    public int getStartKH(int soTrang) {
        int end = soTrang * 10;
        int start = end - 10 + 1;
        return start;
    }

    public int getEndKH(int soTrang) {
        int end = soTrang * 10;

        return end;
    }

    public int getStartHD(int soTrang) {
        int end = soTrang * 4;
        int start = end - 4 + 1;
        return start;
    }

    public int getEndHD(int soTrang) {
        int end = soTrang * 4;

        return end;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jplKhachHang = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKhachHang = new javax.swing.JTable();
        btnDauKH = new javax.swing.JButton();
        btnPrevKH = new javax.swing.JButton();
        btnNextKH = new javax.swing.JButton();
        btnCuoiKH = new javax.swing.JButton();
        lblSoTrangKH = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        txtSoDienThoai = new javax.swing.JTextField();
        cboTrangThai = new javax.swing.JComboBox<>();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        txtTimKiem = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        btnDauHD = new javax.swing.JButton();
        btnPrevHD = new javax.swing.JButton();
        btnNextHD = new javax.swing.JButton();
        btnCuoiHD = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        lblSoTrangHD = new javax.swing.JLabel();
        jplMuaHang = new javax.swing.JPanel();

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jplKhachHang.setBackground(new java.awt.Color(255, 255, 255));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách khách hàng"));
        jPanel12.setEnabled(false);

        tblKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Họ tên", "Số điện thoại", "Ngày thêm", "Ngày sửa", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhachHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKhachHang);

        btnDauKH.setText("Đầu");
        btnDauKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDauKHMouseClicked(evt);
            }
        });

        btnPrevKH.setText("<");
        btnPrevKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPrevKHMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPrevKHMouseEntered(evt);
            }
        });
        btnPrevKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevKHActionPerformed(evt);
            }
        });

        btnNextKH.setText(">");
        btnNextKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNextKHMouseClicked(evt);
            }
        });
        btnNextKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextKHActionPerformed(evt);
            }
        });

        btnCuoiKH.setText("Cuối");
        btnCuoiKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCuoiKHMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnDauKH)
                .addGap(18, 18, 18)
                .addComponent(btnPrevKH, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSoTrangKH, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNextKH, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCuoiKH)
                .addGap(340, 340, 340))
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1027, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSoTrangKH, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNextKH)
                        .addComponent(btnPrevKH)
                        .addComponent(btnCuoiKH)
                        .addComponent(btnDauKH)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Họ tên");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Số điện thoại");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Trạng thái");

        cboTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Khách hàng mới", "Khách hàng tiềm năng", "Khách hàng thân thiết" }));

        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Them.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Sua.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Xoa.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Untitled-1.png"))); // NOI18N
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        txtTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTimKiem)
                    .addComponent(jLabel1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel4)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSoDienThoai, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(txtHoTen))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(30, 30, 30)
                        .addComponent(cboTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(txtTimKiem)))
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua)
                    .addComponent(btnXoa))
                .addGap(24, 24, 24))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnSua, btnThem, btnXoa});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnThem)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(btnXoa))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnSua))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTimKiem)
                            .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel7))
                                    .addComponent(cboTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách khách hàng"));
        jPanel13.setEnabled(false);

        btnDauHD.setText("Đầu");
        btnDauHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDauHDMouseClicked(evt);
            }
        });

        btnPrevHD.setText("<");
        btnPrevHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPrevHDMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPrevHDMouseEntered(evt);
            }
        });
        btnPrevHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevHDActionPerformed(evt);
            }
        });

        btnNextHD.setText(">");
        btnNextHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNextHDMouseClicked(evt);
            }
        });
        btnNextHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextHDActionPerformed(evt);
            }
        });

        btnCuoiHD.setText("Cuối");
        btnCuoiHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCuoiHDMouseClicked(evt);
            }
        });

        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên khách hàng", "Số điện thoại", "Tên hóa đơn", "Tổng tiền", "Ngày mua hàng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDonMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblHoaDon);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1032, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                        .addGap(396, 396, 396)
                        .addComponent(btnDauHD)
                        .addGap(18, 18, 18)
                        .addComponent(btnPrevHD, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblSoTrangHD, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnNextHD, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCuoiHD)
                        .addGap(319, 319, 319)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNextHD)
                    .addComponent(btnPrevHD)
                    .addComponent(btnCuoiHD)
                    .addComponent(btnDauHD)
                    .addComponent(lblSoTrangHD, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jplKhachHangLayout = new javax.swing.GroupLayout(jplKhachHang);
        jplKhachHang.setLayout(jplKhachHangLayout);
        jplKhachHangLayout.setHorizontalGroup(
            jplKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jplKhachHangLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jplKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38))
        );
        jplKhachHangLayout.setVerticalGroup(
            jplKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jplKhachHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Thông tin khách hàng", jplKhachHang);

        jplMuaHang.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jplMuaHangLayout = new javax.swing.GroupLayout(jplMuaHang);
        jplMuaHang.setLayout(jplMuaHangLayout);
        jplMuaHangLayout.setHorizontalGroup(
            jplMuaHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1146, Short.MAX_VALUE)
        );
        jplMuaHangLayout.setVerticalGroup(
            jplMuaHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 766, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Lịch sử mua hàng", jplMuaHang);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhachHangMouseClicked
        index = tblKhachHang.getSelectedRow();
        fillToText();
        _idKhachHang = listQLKH.get(index).getIdKhachHang();
        _soTrangHD = 1;
        listHDKH = khachHangServices.getHoaDonKH(_idKhachHang, getStartHD(_soTrangHD), getEndHD(_soTrangHD));
        loadDataHD(listHDKH);
        lblSoTrangHD.setText(_soTrangHD + "");

    }//GEN-LAST:event_tblKhachHangMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        int hoi = JOptionPane.showConfirmDialog(this, "Bạn có muốn thêm không?");
        if (hoi != JOptionPane.YES_OPTION) {
            return;
        }
        if (txtHoTen.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ họ tên");
            return;
        }
        String hoTen = txtHoTen.getText();
        if (txtSoDienThoai.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số điện thoại");
            return;
        }
        if (khachHangServices.checkSDTMatch(txtSoDienThoai.getText())) {
            JOptionPane.showMessageDialog(this, "Số điện thoại này đã tồn tại");
            return;
        }
        String regex = "(84|0[3|5|7|8|9])+([0-9]{8})";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(txtSoDienThoai.getText());
        boolean check = matcher.matches();
        if (check == false) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số điện thoại của Việt Nam");
            return;
        }
        String soDienThoai = txtSoDienThoai.getText();
        int trangThai = 0;
        if (cboTrangThai.getSelectedIndex() == 0) {
            trangThai = 0;
        }
        if (cboTrangThai.getSelectedIndex() == 1) {
            trangThai = 1;
        }
        if (cboTrangThai.getSelectedIndex() == 2) {
            trangThai = 2;
        }
        QLKhachHang qLKhachHang = new QLKhachHang();
        qLKhachHang.setHoTen(hoTen);
        qLKhachHang.setSoDienThoai(soDienThoai);
        qLKhachHang.setTrangThai(trangThai);
        JOptionPane.showMessageDialog(this, khachHangServices.save(qLKhachHang));
        _soTrangKH = 1;
        listQLKH = khachHangServices.search(name, getStartKH(_soTrangKH), getEndKH(_soTrangKH));
        loadData(listQLKH);
        lblSoTrangKH.setText(_soTrangKH + "");
    }//GEN-LAST:event_btnThemActionPerformed

    private void tblHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblHoaDonMouseClicked

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        int hoi = JOptionPane.showConfirmDialog(this, "Bạn có muốn sửa không?");
        if (hoi != JOptionPane.YES_OPTION) {
            return;
        }
        if (txtHoTen.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ họ tên");
            return;
        }
        String hoTen = txtHoTen.getText();
        if (txtSoDienThoai.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số điện thoại");
            return;
        }
        if (khachHangServices.checkSDTMatch(txtSoDienThoai.getText())) {
            JOptionPane.showMessageDialog(this, "Số điện thoại này đã tồn tại");
            return;
        }
        String regex = "(84|0[3|5|7|8|9])+([0-9]{8})";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(txtSoDienThoai.getText());
        boolean check = matcher.matches();
        if (check == false) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số điện thoại của Việt Nam");
            return;
        }
        String soDienThoai = txtSoDienThoai.getText();
        int trangThai = 0;
        if (cboTrangThai.getSelectedIndex() == 0) {
            trangThai = 0;
        }
        if (cboTrangThai.getSelectedIndex() == 1) {
            trangThai = 1;
        }
        if (cboTrangThai.getSelectedIndex() == 2) {
            trangThai = 2;
        }
        QLKhachHang qLKhachHang = new QLKhachHang();
        qLKhachHang.setIdKhachHang(_idKhachHang);
        qLKhachHang.setHoTen(hoTen);
        qLKhachHang.setSoDienThoai(soDienThoai);
        qLKhachHang.setTrangThai(trangThai);
        JOptionPane.showMessageDialog(this, khachHangServices.update(qLKhachHang));
        listQLKH = khachHangServices.search(name, getStartKH(_soTrangKH), getEndKH(_soTrangKH));
        loadData(listQLKH);
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int hoi = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không?");
        if (hoi != JOptionPane.YES_OPTION) {
            return;
        }
        QLKhachHang qLKhachHang = new QLKhachHang();
        qLKhachHang.setIdKhachHang(_idKhachHang);
        JOptionPane.showMessageDialog(this, khachHangServices.delete(qLKhachHang));
        listQLKH = khachHangServices.search(name, getStartKH(_soTrangKH), getEndKH(_soTrangKH));
        loadData(listQLKH);
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        name = txtTimKiem.getText();
        listQLKH = khachHangServices.search(name, getStartKH(_soTrangKH), getEndKH(_soTrangKH));
        _soTrangKH = 1;
        loadData(listQLKH);
        lblSoTrangKH.setText(_soTrangKH + "");
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked

    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void btnDauKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDauKHMouseClicked
        _soTrangKH = 1;
        listQLKH = khachHangServices.search(name, getStartKH(_soTrangKH), getEndKH(_soTrangKH));
        lblSoTrangKH.setText(String.valueOf(_soTrangKH));
        loadData(listQLKH);
    }//GEN-LAST:event_btnDauKHMouseClicked

    private void btnPrevKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrevKHMouseClicked
        _soTrangKH--;
        int soTrang;
        int soDong = khachHangServices.getSoDong(name);
        double page = soDong % 10.0;
        if (page != 0.0) {
            soTrang = soDong / 10;
            soTrang++;
        } else {
            soTrang = soDong / 10;
        }
        if (_soTrangKH == 0) {
            _soTrangKH = soTrang;
            listQLKH = khachHangServices.search(name, getStartKH(_soTrangKH), getEndKH(_soTrangKH));
            lblSoTrangKH.setText(String.valueOf(_soTrangKH));
            loadData(listQLKH);
        } else {
            listQLKH = khachHangServices.search(name, getStartKH(_soTrangKH), getEndKH(_soTrangKH));
            lblSoTrangKH.setText(String.valueOf(_soTrangKH));
            loadData(listQLKH);
        }
    }//GEN-LAST:event_btnPrevKHMouseClicked

    private void btnPrevKHMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrevKHMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrevKHMouseEntered

    private void btnPrevKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrevKHActionPerformed

    private void btnNextKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextKHMouseClicked
        _soTrangKH++;
        int soTrang;
        int soDong = khachHangServices.getSoDong(name);
        double page = soDong % 10.0;
        if (page != 0.0) {
            soTrang = soDong / 10;
            soTrang++;
        } else {
            soTrang = soDong / 10;
        }
        if (_soTrangKH > soTrang) {
            _soTrangKH = 1;
            listQLKH = khachHangServices.search(name, getStartKH(_soTrangKH), getEndKH(_soTrangKH));
            lblSoTrangKH.setText(String.valueOf(_soTrangKH));
            loadData(listQLKH);
        } else {
            listQLKH = khachHangServices.search(name, getStartKH(_soTrangKH), getEndKH(_soTrangKH));
            lblSoTrangKH.setText(String.valueOf(_soTrangKH));
            loadData(listQLKH);
        }
    }//GEN-LAST:event_btnNextKHMouseClicked

    private void btnNextKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextKHActionPerformed

    }//GEN-LAST:event_btnNextKHActionPerformed

    private void btnCuoiKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCuoiKHMouseClicked
        int soDong = khachHangServices.getSoDong(name);
        double page = soDong % 10.0;
        if (page != 0.0) {
            _soTrangKH = soDong / 10;
            _soTrangKH++;
        } else {
            _soTrangKH = soDong / 10;
        }
        listQLKH = khachHangServices.search(name, getStartKH(_soTrangKH), getEndKH(_soTrangKH));
        lblSoTrangKH.setText(String.valueOf(_soTrangKH));
        loadDataHD(listHDKH);
    }//GEN-LAST:event_btnCuoiKHMouseClicked

    private void btnDauHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDauHDMouseClicked
        _soTrangHD = 1;
        listHDKH = khachHangServices.getHoaDonKH(_idKhachHang, getStartHD(_soTrangHD), getEndHD(_soTrangHD));
        lblSoTrangHD.setText(String.valueOf(_soTrangHD));
        loadDataHD(listHDKH);
    }//GEN-LAST:event_btnDauHDMouseClicked

    private void btnPrevHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrevHDMouseClicked
        _soTrangHD--;
        int soTrang;
        int soDong = khachHangServices.getSoDongHD(_idKhachHang);
        double page = soDong % 4.0;
        if (page != 0.0) {
            soTrang = soDong / 4;
            soTrang++;
        } else {
            soTrang = soDong / 4;
        }
        if (_soTrangHD == 0) {
            _soTrangHD = soTrang;
            listHDKH = khachHangServices.getHoaDonKH(_idKhachHang, getStartHD(_soTrangHD), getEndHD(_soTrangHD));
            lblSoTrangHD.setText(String.valueOf(_soTrangHD));
            loadDataHD(listHDKH);
        } else {
            listHDKH = khachHangServices.getHoaDonKH(_idKhachHang, getStartHD(_soTrangHD), getEndHD(_soTrangHD));
            lblSoTrangHD.setText(String.valueOf(_soTrangHD));
            loadDataHD(listHDKH);
        }
    }//GEN-LAST:event_btnPrevHDMouseClicked

    private void btnPrevHDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrevHDMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrevHDMouseEntered

    private void btnPrevHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevHDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrevHDActionPerformed

    private void btnNextHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextHDMouseClicked
        _soTrangHD++;
        int soTrang;
        int soDong = khachHangServices.getSoDongHD(_idKhachHang);
        double page = soDong % 4.0;
        if (page != 0.0) {
            soTrang = soDong / 4;
            soTrang++;
        } else {
            soTrang = soDong / 4;
        }
        if (_soTrangHD > soTrang) {
            _soTrangHD = 1;
            listHDKH = khachHangServices.getHoaDonKH(_idKhachHang, getStartHD(_soTrangHD), getEndHD(_soTrangHD));
            lblSoTrangHD.setText(String.valueOf(_soTrangHD));
            loadDataHD(listHDKH);
        } else {
            listHDKH = khachHangServices.getHoaDonKH(_idKhachHang, getStartHD(_soTrangHD), getEndHD(_soTrangHD));
            lblSoTrangHD.setText(String.valueOf(_soTrangHD));
            loadDataHD(listHDKH);
        }
    }//GEN-LAST:event_btnNextHDMouseClicked

    private void btnNextHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextHDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNextHDActionPerformed

    private void btnCuoiHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCuoiHDMouseClicked
        int soDong = khachHangServices.getSoDongHD(_idKhachHang);
        double page = soDong % 4.0;
        if (page != 0.0) {
            _soTrangHD = soDong / 4;
            _soTrangHD++;
        } else {
            _soTrangHD = soDong / 4;
        }
        listHDKH = khachHangServices.getHoaDonKH(_idKhachHang, getStartHD(_soTrangHD), getEndHD(_soTrangHD));
        lblSoTrangHD.setText(String.valueOf(_soTrangHD));
        loadDataHD(listHDKH);
    }//GEN-LAST:event_btnCuoiHDMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCuoiHD;
    private javax.swing.JButton btnCuoiKH;
    private javax.swing.JButton btnDauHD;
    private javax.swing.JButton btnDauKH;
    private javax.swing.JButton btnNextHD;
    private javax.swing.JButton btnNextKH;
    private javax.swing.JButton btnPrevHD;
    private javax.swing.JButton btnPrevKH;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboTrangThai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel jplKhachHang;
    private javax.swing.JPanel jplMuaHang;
    private javax.swing.JLabel lblSoTrangHD;
    private javax.swing.JLabel lblSoTrangKH;
    private javax.swing.JTable tblHoaDon;
    private javax.swing.JTable tblKhachHang;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtSoDienThoai;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables

    private void loadData(List<QLKhachHang> listQLKH) {
        model = (DefaultTableModel) tblKhachHang.getModel();
        model.setRowCount(0);
        for (QLKhachHang qLKhachHang : listQLKH) {
            model.addRow(new Object[]{
                qLKhachHang.getHoTen(),
                qLKhachHang.getSoDienThoai(),
                qLKhachHang.getNgayThem(),
                qLKhachHang.getNgaySua(),
                convertTrangThai(qLKhachHang.getTrangThai())
            });
        }
    }

//    public void fillToTableKhachHangIndex(List<QLKhachHang> lstKhachHang, int index) {
//        if (lstKhachHang.isEmpty()) {
//            System.out.println("List KH Rong");
//            model.setRowCount(0);
//        } else {
//            model = (DefaultTableModel) tblKhachHang.getModel();
//            model.setRowCount(0);
//            int end = index * 10;
//            int start = end - 10;
//            if (lstKhachHang.size() < end) {
//                end = lstKhachHang.size();
//            }
//            for (int i = start; i < end; i++) {
//                model.addRow(new Object[]{
//                    lstKhachHang.get(i).getHoTen(),
//                    lstKhachHang.get(i).getSoDienThoai(),
//                    lstKhachHang.get(i).getNgayThem(),
//                    lstKhachHang.get(i).getNgaySua(),
//                    convertTrangThai(lstKhachHang.get(i).getTrangThai())});
//            }
//        }
//
//    }
//    private void searchData(ArrayList<QLKhachHang> list){
//        model = (DefaultTableModel) tblKhachHang.getModel();
//        model.setRowCount(0);
//        for (QLKhachHang qLKhachHang : list) {
//            model.addRow(new Object[]{
//                qLKhachHang.getHoTen(),
//                qLKhachHang.getSoDienThoai(),
//                qLKhachHang.getNgayThem(),
//                qLKhachHang.getNgaySua(),
//                convertTrangThai(qLKhachHang.getTrangThai())
//            });
//        }
//    }
    private String convertTrangThai(int trangThai) {
        if (trangThai == 0) {
            return "Khách hàng mới";
        }
        if (trangThai == 1) {
            return "Khách hàng tiềm năng";
        }
        return "Khách hàng thân thiết";
    }

//    public void fillToTablehoaDonIndex(List<HoaDonKhachHangView> listHDKH, int index) {
//        if (listHDKH.isEmpty()) {
//            System.out.println("List HD Rong");
//            model2.setRowCount(0);
//        } else {
//            model2 = (DefaultTableModel) tblHoaDon.getModel();
//            model2.setRowCount(0);
//            int end = index * 4;
//            int start = end - 4;
//            if (listHDKH.size() < end) {
//                end = listHDKH.size();
//            }
//            for (int i = start; i < end; i++) {
//                model2.addRow(new Object[]{
//                    listHDKH.get(i).getHoTen(),
//                    listHDKH.get(i).getSoDienThoai(),
//                    listHDKH.get(i).getTenHoaDon(),
//                    listHDKH.get(i).getTongTien(),
//                    listHDKH.get(i).getNgayMuaHang()});
//            }
//        }
//
//    }
    private void loadDataHD(List<HoaDonKhachHangView> listHDKH) {
        model2 = (DefaultTableModel) tblHoaDon.getModel();
        model2.setRowCount(0);
        for (HoaDonKhachHangView hoaDonKhachHangView : listHDKH) {
            model2.addRow(new Object[]{
                hoaDonKhachHangView.getHoTen(),
                hoaDonKhachHangView.getSoDienThoai(),
                hoaDonKhachHangView.getTenHoaDon(),
                hoaDonKhachHangView.getTongTien(),
                hoaDonKhachHangView.getNgayMuaHang()
            });
        }
    }

    private void fillToText() {
        txtHoTen.setText(String.valueOf(tblKhachHang.getValueAt(index, 0)));
        txtSoDienThoai.setText(String.valueOf(tblKhachHang.getValueAt(index, 1)));
        cboTrangThai.setSelectedItem(tblKhachHang.getValueAt(index, 4));
    }
}
