/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;

import Services.NhapHangServices;
import Services.NhapHangServicesImpl;
import ViewModels.HoaDonNhapHangChiTietView;
import ViewModels.HoaDonNhapHangViews;
import ViewModels.SanPhamView;
import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class NhapHangJPanel extends javax.swing.JPanel {

    NhapHangServices nhapHangServices = new NhapHangServicesImpl();
    DefaultTableModel model;
    DefaultTableModel model2;
    DefaultTableModel model3;
    String _idHoaDon = "";
    int index;
    int indexHDCT;
    String idNhanVien = LoginJFrame._idAccountLogin;

    public NhapHangJPanel() {
        initComponents();
        loadData();
        model2 = (DefaultTableModel) tblHoaDonChiTiet.getModel();
        model2.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jblNhap = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblHoaDonChiTiet = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtSoLuongThucTe = new javax.swing.JTextField();
        btnXacNhan = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtGhiChu = new javax.swing.JTextArea();
        btnHoanThanh = new javax.swing.JButton();
        jblXuat = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSoLuongTon = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1100, 780));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseEntered(evt);
            }
        });

        jblNhap.setBackground(new java.awt.Color(255, 255, 255));
        jblNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblNhapMouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Hóa đơn"));

        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nhân viên kho", "Tên hóa đơn", "Ngày tạo đơn"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDonMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblHoaDon);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 931, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Hóa đơn chi tiết"));

        tblHoaDonChiTiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tên sản phẩm", "Kích thước", "Số lượng", "Số lượng thực tế"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHoaDonChiTiet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDonChiTietMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblHoaDonChiTiet);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 949, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Số lượng");

        txtSoLuongThucTe.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSoLuongThucTe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoLuongThucTeActionPerformed(evt);
            }
        });

        btnXacNhan.setBackground(new java.awt.Color(0, 255, 51));
        btnXacNhan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXacNhan.setText("Xác nhận");
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSoLuongThucTe, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSoLuongThucTe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnXacNhan))
                .addGap(50, 50, 50))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Ghi chú");

        txtGhiChu.setColumns(20);
        txtGhiChu.setRows(5);
        jScrollPane1.setViewportView(txtGhiChu);

        btnHoanThanh.setBackground(new java.awt.Color(0, 255, 51));
        btnHoanThanh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHoanThanh.setText("Hoàn thành");
        btnHoanThanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoanThanhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHoanThanh, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addComponent(btnHoanThanh)
                            .addGap(12, 12, 12))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jblNhapLayout = new javax.swing.GroupLayout(jblNhap);
        jblNhap.setLayout(jblNhapLayout);
        jblNhapLayout.setHorizontalGroup(
            jblNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jblNhapLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jblNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jblNhapLayout.createSequentialGroup()
                        .addGroup(jblNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jblNhapLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(59, 59, 59))
                    .addGroup(jblNhapLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jblNhapLayout.setVerticalGroup(
            jblNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jblNhapLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jblNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(232, 232, 232))
        );

        jTabbedPane1.addTab("Hàng chờ", jblNhap);

        jblXuat.setBackground(new java.awt.Color(255, 255, 255));
        jblXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblXuatMouseClicked(evt);
            }
        });

        tblSoLuongTon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên sản phẩm", "Kích thước", "Số lượng tồn"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblSoLuongTon);

        javax.swing.GroupLayout jblXuatLayout = new javax.swing.GroupLayout(jblXuat);
        jblXuat.setLayout(jblXuatLayout);
        jblXuatLayout.setHorizontalGroup(
            jblXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jblXuatLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1022, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jblXuatLayout.setVerticalGroup(
            jblXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jblXuatLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(228, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Số lượng tồn", jblXuat);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        model3 = (DefaultTableModel) tblSoLuongTon.getModel();
        model3.setRowCount(0);
        ArrayList<SanPhamView> listSP = nhapHangServices.getSoLuongTon();
        for (SanPhamView sanPhamView : listSP) {
            model3.addRow(new Object[]{
                sanPhamView.getTenSanPham(),
                sanPhamView.getKichThuoc(),
                sanPhamView.getSoLuongTon()
            });
        }
        tblSoLuongTon.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                final Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                c.setBackground(Color.white);
                c.setForeground(Color.black);

                return c;
            }
        });
        for (int i = 0; i < listSP.size(); i++) {
            int rows = i;
            if (listSP.get(i).getSoLuongTon() < 20) {
                tblSoLuongTon.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
                    @Override
                    public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                        final Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                        if (row <= rows) {
                            c.setBackground(Color.red);
                        } else {
                            c.setBackground(Color.white);
                            c.setForeground(Color.black);
                        }
                        return c;
                    }
                });
            }
        }
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jTabbedPane1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1MouseEntered

    private void jblXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblXuatMouseClicked

    }//GEN-LAST:event_jblXuatMouseClicked

    private void jblNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblNhapMouseClicked

    }//GEN-LAST:event_jblNhapMouseClicked

    private void tblHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonMouseClicked
        index = tblHoaDon.getSelectedRow();
        loadData2();
    }//GEN-LAST:event_tblHoaDonMouseClicked

    private void btnHoanThanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoanThanhActionPerformed
        int hoi = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn hoàn thành?");
        if (hoi != JOptionPane.YES_OPTION) {
            return;
        }
        if (txtGhiChu.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập ghi chú");
            return;
        }
        String ghiChu = txtGhiChu.getText();
        ArrayList<HoaDonNhapHangChiTietView> listHDCT = nhapHangServices.getHDCT(_idHoaDon);
        boolean check = true;
        for (int i = 0; i < listHDCT.size(); i++) {
            if (listHDCT.get(i).getSoLuong() != listHDCT.get(i).getSoLuongThucTe()) {
                check = false;
            }
        }

        if (check) {
            JOptionPane.showMessageDialog(this, nhapHangServices.updateHD(ghiChu, _idHoaDon, idNhanVien));
        } else {
            JOptionPane.showMessageDialog(this, nhapHangServices.updateHDFailed(ghiChu, _idHoaDon, idNhanVien));
        }
        nhapHangServices.updateSoLuongTon(listHDCT);
        loadData();
        model2.setRowCount(0);
    }//GEN-LAST:event_btnHoanThanhActionPerformed

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        int hoi = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xác nhận?");
        if (hoi != JOptionPane.YES_OPTION) {
            return;
        }
        String _tenSanPham = tblHoaDonChiTiet.getValueAt(indexHDCT, 0).toString();
        int _kichThuoc = Integer.parseInt(tblHoaDonChiTiet.getValueAt(indexHDCT, 1).toString());
        String idSanPham = nhapHangServices.getID(_tenSanPham, _kichThuoc);
        int soLuongThucTe = 0;
        if (txtSoLuongThucTe.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số lượng");
            return;
        }
        try {
            soLuongThucTe = Integer.parseInt(txtSoLuongThucTe.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số lượng là số");
            return;
        }

        JOptionPane.showMessageDialog(this, nhapHangServices.update(_idHoaDon, idSanPham, soLuongThucTe));

        loadData2();


    }//GEN-LAST:event_btnXacNhanActionPerformed

    private void txtSoLuongThucTeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoLuongThucTeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoLuongThucTeActionPerformed

    private void tblHoaDonChiTietMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonChiTietMouseClicked
        indexHDCT = tblHoaDonChiTiet.getSelectedRow();
    }//GEN-LAST:event_tblHoaDonChiTietMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHoanThanh;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel jblNhap;
    private javax.swing.JPanel jblXuat;
    private javax.swing.JTable tblHoaDon;
    private javax.swing.JTable tblHoaDonChiTiet;
    private javax.swing.JTable tblSoLuongTon;
    private javax.swing.JTextArea txtGhiChu;
    private javax.swing.JTextField txtSoLuongThucTe;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
        model = (DefaultTableModel) tblHoaDon.getModel();
        model.setRowCount(0);
        ArrayList<HoaDonNhapHangViews> listHD = nhapHangServices.findAll();
        for (HoaDonNhapHangViews hoaDonNhapHangViews : listHD) {
            model.addRow(new Object[]{
                hoaDonNhapHangViews.getnhanVienKho(),
                hoaDonNhapHangViews.getTenHoaDon(),
                //                hoaDonNhapHangViews.getNhaCungUng(),
                //                hoaDonNhapHangViews.getTongTien(),
                hoaDonNhapHangViews.getNgayThem()
            });
        }
    }

    private void loadData2() {
        model2 = (DefaultTableModel) tblHoaDonChiTiet.getModel();
        model2.setRowCount(0);
        ArrayList<HoaDonNhapHangViews> listHD = nhapHangServices.findAll();
        _idHoaDon = listHD.get(index).getIdHoaDon();
        ArrayList<HoaDonNhapHangChiTietView> listHDCT = nhapHangServices.getHDCT(_idHoaDon);
        if (listHDCT.size() == 0) {
            return;
        }
        for (HoaDonNhapHangChiTietView hoaDonNhapHangChiTietView : listHDCT) {
            model2.addRow(new Object[]{
                hoaDonNhapHangChiTietView.getTenSanPham(),
                hoaDonNhapHangChiTietView.getKichThuoc(),
                hoaDonNhapHangChiTietView.getSoLuong(),
                hoaDonNhapHangChiTietView.getSoLuongThucTe(),
                hoaDonNhapHangChiTietView.getDonGia()
            });
        }
    }

}
