/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;

import DomainModels.KhuyenMai;
import Services.KhuyenMaiService;
import Services.KhuyenMaiServiceImpl;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class QuanLyKhuyenMaiJPanel extends javax.swing.JPanel {

    KhuyenMaiService khuyenMaiService=new KhuyenMaiServiceImpl();
    DefaultTableModel model=new DefaultTableModel();
    
    /**
     * Creates new form TrangChuJPanel
     */
    public QuanLyKhuyenMaiJPanel() {
        initComponents();
        
        
        loadData();  
        loadTrangThai();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKhuyenMai = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTenKhuyenMai = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cboTinhTrang = new javax.swing.JComboBox<>();
        txtSoLanApDung = new javax.swing.JTextField();
        txtTrietKhau = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1100, 780));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách khuyến mãi"));

        tblKhuyenMai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id khuyến mãi", "Tên khuyến mãi", "Số lần áp dụng", "Chiết khấu", "Tình trạng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblKhuyenMai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhuyenMaiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKhuyenMai);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 937, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Tạo khuyến mãi"));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Tên khuyến mãi");

        txtTenKhuyenMai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Số lần áp dụng");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Chiết khấu");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Tình trạng");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Id");

        cboTinhTrang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboTinhTrang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ngừng hoạt động", "Còn hoạt động" }));
        cboTinhTrang.setEnabled(false);
        cboTinhTrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTinhTrangActionPerformed(evt);
            }
        });

        txtSoLanApDung.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtTrietKhau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(76, 76, 76)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTrietKhau)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 135, Short.MAX_VALUE))
                    .addComponent(txtTenKhuyenMai)
                    .addComponent(txtSoLanApDung)
                    .addComponent(cboTinhTrang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(74, 74, 74))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblId))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTenKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSoLanApDung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTrietKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cboTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnThem.setBackground(new java.awt.Color(234, 162, 96));
        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Them.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(234, 162, 96));
        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Sua.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(234, 162, 96));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Xoa.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua)
                    .addComponent(btnXoa))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnSua, btnThem, btnXoa});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnThem)
                .addGap(49, 49, 49)
                .addComponent(btnSua)
                .addGap(55, 55, 55)
                .addComponent(btnXoa)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 276, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 800));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblKhuyenMaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhuyenMaiMouseClicked
        int index=tblKhuyenMai.getSelectedRow();
        lblId.setText(tblKhuyenMai.getValueAt(index, 0).toString());
        txtTenKhuyenMai.setText(tblKhuyenMai.getValueAt(index, 1).toString());
        txtSoLanApDung.setText(tblKhuyenMai.getValueAt(index, 2).toString());
        txtTrietKhau.setText(tblKhuyenMai.getValueAt(index, 3).toString());
        cboTinhTrang.setSelectedItem(tblKhuyenMai.getValueAt(index, 4).toString());
    }//GEN-LAST:event_tblKhuyenMaiMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        
        if(txtTenKhuyenMai.getText().trim().equals("") || txtSoLanApDung.getText().trim().equals("") || txtTrietKhau.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this, "Vui lòng không để trống");
            return;
        }
        String ten=txtTenKhuyenMai.getText();
        for(int i=0;i<khuyenMaiService.getList().size();i++){
            if(ten.trim().equals(khuyenMaiService.getList().get(i).getTenKhuyenMai())){
                JOptionPane.showMessageDialog(this, "Khuyến mãi đã tồn tại");
                return;
            }
        }
        int soLanDung;
        try {
            soLanDung=Integer.parseInt(txtSoLanApDung.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "vui lòng nhập số lần là số nguyên");
            return;
        }
        if(soLanDung<0){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số lần > 0");
            return;
        }
        int chietKhau;
        try {
            chietKhau=Integer.parseInt(txtTrietKhau.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "vui lòng nhập chiết khấu là số nguyên");
            return;
        }
        if(chietKhau<0){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập chiết khâu >=0");
            return;
        }
        int tinhTrang;
        if(Integer.parseInt(txtSoLanApDung.getText())==0){
            tinhTrang=0;
        }else{
            tinhTrang=1;
        }
        int hoi = JOptionPane.showConfirmDialog(this, "Bạn có muốn thêm không?");
        if(hoi != JOptionPane.YES_OPTION){
            return;
        }
        KhuyenMai km=new KhuyenMai(null, ten, null, null, soLanDung, chietKhau, tinhTrang);
        JOptionPane.showMessageDialog(this, khuyenMaiService.insert(km));
        loadData();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        int index=tblKhuyenMai.getSelectedRow();
        if(index==-1){
            JOptionPane.showMessageDialog(this, "Vui lòng chọn khuyến mãi cần sửa");
            return;
        }
        if(txtTenKhuyenMai.getText().trim().equals("") || txtSoLanApDung.getText().trim().equals("") || txtTrietKhau.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this, "Vui lòng không để trống");
            return;
        }
        String id=lblId.getText();
        String ten=txtTenKhuyenMai.getText();
        int soLanDung;
        try {
            soLanDung=Integer.parseInt(txtSoLanApDung.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "vui lòng nhập số lần là số nguyên");
            return;
        }
        if(soLanDung<0){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số lần > 0");
            return;
        }
        int chietKhau;
        try {
            chietKhau=Integer.parseInt(txtTrietKhau.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "vui lòng nhập chiết khấu là số nguyên");
            return;
        }
        if(chietKhau<0){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập chiết khâu >=0");
            return;
        }
        int tinhTrang;
        if(Integer.parseInt(txtSoLanApDung.getText())==0){
            tinhTrang=0;
        }else{
            tinhTrang=1;
        }
        int hoi = JOptionPane.showConfirmDialog(this, "Bạn có muốn sửa không?");
        if(hoi != JOptionPane.YES_OPTION){
            return;
        }
        KhuyenMai km=new KhuyenMai(id, ten, null, null, soLanDung, chietKhau, tinhTrang);
        JOptionPane.showMessageDialog(this, khuyenMaiService.update(km));
        loadData();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int index=tblKhuyenMai.getSelectedRow();
        if(index==-1){
            JOptionPane.showMessageDialog(this, "Vui lòng chọn khuyến mãi cần xóa");
            return;
        }
        int hoi=JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không");
        if(hoi==JOptionPane.NO_OPTION || hoi==JOptionPane.CANCEL_OPTION || hoi==JOptionPane.CLOSED_OPTION){
            return;
        }
        String id=lblId.getText();
        JOptionPane.showMessageDialog(this, khuyenMaiService.delete(id));
        loadData();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void cboTinhTrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTinhTrangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboTinhTrangActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboTinhTrang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblId;
    private javax.swing.JTable tblKhuyenMai;
    private javax.swing.JTextField txtSoLanApDung;
    private javax.swing.JTextField txtTenKhuyenMai;
    private javax.swing.JTextField txtTrietKhau;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
        model=(DefaultTableModel) tblKhuyenMai.getModel();
        model.setRowCount(0);
        ArrayList list=khuyenMaiService.getList();
        for(KhuyenMai km : khuyenMaiService.getList()){
            model.addRow(new Object[]{km.getIdKhuyenMai(),km.getTenKhuyenMai(),km.getSoLanApDung(),km.getChietKhau(),this.getTinhTrang(km.getTinhTrang())});
        }
    }
    public String getTinhTrang(int tinhTrang){
        if(tinhTrang==0){
            return "Ngừng hoạt động";
        }return "Còn hoạt động";
    }

    private void loadTrangThai() {
        ArrayList<KhuyenMai> lstKM=khuyenMaiService.getList();
        for(int i=0;i<tblKhuyenMai.getRowCount();i++){
            int soLan=Integer.parseInt(tblKhuyenMai.getValueAt(i, 2).toString());
            if(soLan==0){
                int tinhTrang=0;
                KhuyenMai km=new KhuyenMai(lstKM.get(i).getIdKhuyenMai(), null, null, null, soLan, WIDTH, tinhTrang);
                khuyenMaiService.updateTrangThai(km);
            }
        }
    }
}
